export const USERNAME_OR_PASSWORD_IS_REQUIRED = 'username or password is required'
export const USERNAME_EXISTS = 'username exists'
export const USERNAME_DOES_NOT_EXISTS = 'username does not exists'
export const PASSWORD_ERROR = 'password error'
export const UNAUTHORIZATION = 'unauthorization'
